/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "inverse-primary": "#adcec1",
        "surface-container-low": "#f2f4f6",
        "surface-container": "#eceef0",
        "on-secondary-container": "#57657a",
        "on-primary-container": "#75958a",
        "inverse-surface": "#2d3133",
        "secondary": "#515f74",
        "on-error": "#ffffff",
        "surface-tint": "#46645b",
        "secondary-fixed": "#d5e3fc",
        "on-background": "#191c1e",
        "tertiary": "#00170c",
        "surface": "#f7f9fb",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#b9c7df",
        "primary-container": "#0d2c24",
        "on-secondary-fixed-variant": "#3a485b",
        "inverse-on-surface": "#eff1f3",
        "on-surface": "#191c1e",
        "surface-container-high": "#e6e8ea",
        "outline-variant": "#c1c8c4",
        "on-tertiary-fixed-variant": "#0e5138",
        "on-primary-fixed-variant": "#2f4c43",
        "surface-bright": "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#414845",
        "on-primary-fixed": "#012019",
        "primary-fixed": "#c8eadd",
        "primary-fixed-dim": "#adcec1",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "outline": "#727975",
        "on-tertiary-fixed": "#002114",
        "background": "#f7f9fb",
        "tertiary-container": "#002e1d",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#b1f0ce",
        "surface-variant": "#e0e3e5",
        "on-tertiary-container": "#5e9b7c",
        "on-secondary-fixed": "#0d1c2e",
        "surface-container-highest": "#e0e3e5",
        "secondary-container": "#d5e3fc",
        "surface-dim": "#d8dadc",
        "tertiary-fixed-dim": "#95d4b3",
        "primary": "#001610",
        "error-container": "#ffdad6"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter": "24px",
        "md": "24px",
        "lg": "40px",
        "sm": "12px",
        "xl": "64px",
        "xs": "4px",
        "margin": "32px",
        "base": "8px",
        "max_width": "1280px"
      },
      fontFamily: {
        "body-md": ["Inter"],
        "code-data": ["Space Grotesk"],
        "label-caps": ["Inter"],
        "h1": ["Space Grotesk"],
        "h2": ["Space Grotesk"],
        "h3": ["Space Grotesk"],
        "body-lg": ["Inter"]
      },
      fontSize: {
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "code-data": ["14px", {"lineHeight": "1.0", "fontWeight": "500"}],
        "label-caps": ["12px", {"lineHeight": "1.0", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "h3": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "h2": ["36px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "h1": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
